import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { SFPro } from "@/lib/helper/fonts";
import ClientProviders from "@/lib/client-providers";
import '@ant-design/v5-patch-for-react-19';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SFPro.variable} antialiased`}
      >
        <AntdRegistry>
          <ClientProviders>
            {children}
          </ClientProviders>
        </AntdRegistry>
      </body>
    </html>
  );
}
